# -*- coding: utf-8 -*-
"""Exercícios Extras

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnbfdE6PtAw0gAFPUjx9iIYbLVYEuLPD

1. Fazer um algoritmo para ler o valor do lado de um quadrado e mostrar sua área
( lado2
) e seu perímetro ( 4 x lado ).
"""

lado = float(input("Digite o lado do quadrado: "))
area = lado ** 2
perimetro = lado * 4
print(f"A área desse quadrado é {area} e o perímetro é {perimetro}")

"""2. Elaborar um algoritmo para ler o nome e a quantidade de filhos de uma pessoa.
Mostrar a mensagem: “Fulano tem 5 filhos.”
"""

nome = str(input("Digite um nome: "))
quant_filhos = int(input("Digite uma quantidade de filhos: "))
print(f"{nome} tem {quant_filhos} filhos")

"""3. Fazer um algoritmo para ler os valores da base e altura de um retângulo e mostrar
seu perímetro ( 2 x ( base + altura ) ) e sua área ( base x altura ).
"""

base = float(input("Digite o valor da base do retangulo: "))
altura = float(input("Digite o valor da altura do retangulo: "))
perimetro = 2*(base+altura)
area = base * altura
print(f"A área da do retangulo é {area} e o perímetro é {perimetro}")

"""4. Fazer um algoritmo para ler o valor do lado de um cubo e
mostrar sua área ( 6 x lado2

) e seu volume ( lado3
).
"""

lado = float(input("Digite  o valor do lado do cubo: "))
area = 6 * (lado**2)
volume = lado ** 3
print(f"A área do cubo é {area} e o volume é {volume}")

"""5. Elaborar um algoritmo para ler dois números e mostrar o quociente e o resto da
divisão inteira do primeiro pelo segundo número.
"""

num_um = int(input("Digite um número: "))
num_dois = int(input("Digite outro número: "))
quociente = num_um // num_dois
resto = num_um % num_dois
print(f"O quociente é {quociente} e o resto da divisão é {resto}")

"""6. Criar um algoritmo para ler a base e a altura de um triângulo e
mostrar a sua área ( ( base x altura ) / 2 ).
"""

base = float(input("Digite a sua base do triângulo: "))
altura = float(input("Digite a altura do triângulo: "))
area = (base * altura) / 2
print(f"O valor da área do triângulo é {area}")

"""7. Construir um algoritmo para ler o raio de uma circunferência e
mostrar o perímetro ( 2 x π x raio ) e a área ( π x raio2

). Utilize o π

como constante.
"""

raio = float(input("Digite o valor do raio: "))
perimetro = 2 * raio
area = raio**2
print(f"O perímetro da circuferencia é {perimetro}π e a área é {area}π")