# -*- coding: utf-8 -*-
"""Exercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0_v5K83aIHedhcwK3HBjyXWZIVwlPRe

1) Faça um algoritmo que leia dois números e mostre o produto desses números.
"""

print("PROGRAMA QUE MOSTRA O PRODUTO DE DOIS NÚMEROS!")
n1 = float(input("Digite um número: "))
n2 = float(input("Digite outro número: "))
resultado = n1 * n2
print("O produto desses números é:", resultado)

"""2) Faça um algoritmo que leia uma temperatura em graus Fahrenheit e converta e
mostre em graus Centígrados.
"""

grauF = int(input("Digite a temperatura em Fahrenheit: "))
grauC = (grauF - 32) * 5 / 9

print(f"O grau {grauF}° Fahrenheit em Centígrados é {grauC}")

"""3) Faça um algoritmo que leia uma certa quantidade de chuva em polegadas e escreva
o equivalente em milímetros.
FÓRMULA: 25.4 mm = 1 polegada
"""

quant_chuva = int(input("Digite a quantidade de chuva (Polegadas): "))
resultado = quant_chuva * 24.4
print(f"O resultado em milímetros é: {resultado} mm")

"""4) Faça um algoritmo que calcule o volume de uma lata de óleo. Escreva o resultado.
FÓRMULA: volume = p * raio2 * altura
"""

raio = float(input("Digite o raio da lata: "))
altura = float(input("Digite a altura da lata: "))
volume = 3.14 * (raio ** 2) * altura
print(f"O volume da lata de óleo é: {volume:,.2f}")

"""5) Faça um algoritmo que leia as 3 notas de um aluno e calcule e escreva a média final
deste aluno. Considerar que a média é ponderada e que o peso das notas é: 2,3 e 5,
respectivamente.
"""

n1 = float(input("Digite a primeira nota: "))
n2 = float(input("Digite a segunda nota: "))
n3 = float(input("Digite a terceira nota: "))
media = (n1 + n2+ n3) / 3
print(f"A média é {media}")

"""6) Faça um algoritmo que leia as coordenadas de dois pontos, P1 (x1, y1) e P2 (x2, y2)
respectivamente, e calcule e escreva a distância entre eles.
"""

import math
x1  = float(input("Digite a coordenada x1: "))
y1  = float(input("Digite a coordenada y1: "))
x2  = float(input("Digite a coordenada x2: "))
y2  = float(input("Digite a coordenada y2: "))
distancia = math.sqrt((x2 - x1)**2 + (y2 - y1)**2)
print(f"A distancia é {distancia:,.2f}")

"""7) Faça um algoritmo que leia os valores a, b, c, d, e, f, e calcule x e y.

"""

a = float(input("Digite o número A: "))
b = float(input("Digite o número B: "))
c = float(input("Digite o número C: "))
d = float(input("Digite o número D: "))
e = float(input("Digite o número E: "))
f = float(input("Digite o número F: "))

x = ((c*e) - (b*f)) / ((a*e) - (b*d))
y = ((a*f) - (c*d)) / ((a*e) - (b*d))

print(f"O resultado de x é {x}")
print(f"O resultado de y é {y}")

"""8) O custo ao consumidor de um carro novo é a soma do custo de fábrica com a
percentagem do distribuidor e dos impostos (aplicados ao custo de fábrica).
Supondo que a percentagem do distribuidor seja de 28% e os impostos de 45%,
escrever um algoritmo que leia o custo de fábrica de um carro e escreva o custo ao
consumidor.
"""

custo_fabrica = float(input("Digite o custo de fabrica de um carro: "))
perc_dist = custo_fabrica * (28/100)
perc_impos = custo_fabrica * (45/100)
custo_consumidor = custo_fabrica + perc_dist + perc_impos
print(f"O custo do consumidor é: {custo_consumidor}")

"""9) Faça um algoritmo que leia a idade de uma pessoa expressa em dias e mostre-a
expressa em anos, meses e dias.
"""

idade = int(input("Digite a sua idade em dias: "))
ano = idade // 365
mes = (idade % 365) // 30
dia = (idade % 365) % 30
print(f"Você tem {ano} anos, {mes} meses e {dia} dias")

"""10) Faça um algoritmo que leia o tempo de duração de um evento em uma fábrica
expressa em segundos e mostre-o expresso em horas, minutos e segundos.
"""

segds = int(input("Digite o tempo de duração do evento em segundos: "))
horas = segds // 3600
minutos = (segds % 3600) // 60
segundos = (segds % 3600) % 60

print(f"Esse tempo em segundos são {horas} horas {minutos} minutos e {segundos} segundos.")

"""11) O governador acaba de liberar R$ 1.000.000.000,00 para construção de casas
populares. Cada casa custa o equivalente a 90 salários mínimos. Faça um algoritmo
que leia o valor do salário mínimo e calcule a quantidade de casas que podem ser
construídas com o recurso liberado.
"""

salario = float(input("Digite o salário minimo: "))
valor_lib = 1000000000
casa = salario * 90
quant_casa = valor_lib // casa
print(f"A quantidade de casas que podem ser feitas com esse valor são de {quant_casa} casas")

"""12) Faça um algoritmo que leia o salário bruto mensal de um funcionário, calcule e
mostre os valores conforme modelo abaixo:
Salário Bruto :R$
(-) IR (15%) :R$
(-) INSS (11%) :R$
(-) Sindicato (3%) :R$
Salário Líquido :R$
"""

salario_bruto = float(input("Digite o seu salário bruto mensal: "))
IR = salario_bruto * (15/100)
INSS = salario_bruto * (11/100)
sindicato = salario_bruto * (3/100)
salario_liquido = salario_bruto - IR - INSS - sindicato
print("IR: ", IR)
print("INSS: ", INSS)
print("Sindicato: ", sindicato)
print(f"O seu salário líquido é: {salario_liquido}")

"""13) Maria quer saber quantos litros de gasolina precisa colocar em seu carro e quanto
vai gastar para fazer uma viagem até a casa de sua irmã. Faça um algoritmo que
leia:
• A distância da casa de Maria até sua irmã;
• O consumo do carro de Maria (KM rodados / litro);
• O preço da gasolina (litro).
E mostre as informações que Maria necessita.
"""

distancia = float(input("Digite a distancia entre a casa de Maria e a casa de sua irmã (KM): "))
consumo = float(input("Digite o consumo do carro de Maria (KM rodados / Litro): "))
preco_gas = float(input("Digite o preço da gasolina: "))
litro = distancia / consumo
gasto = litro * preco_gas
print(f"Maria vai gastar R${gasto}")

"""14) Faça um algoritmo que leia as medidas dos 4 lados de um terreno, o preço de um
mourão e o preço de um metro de arame farpado. Deve ser escrito:
• o número de mourões necessários para cercar o terreno, colocando um mourão a
cada 3 metros;
• o gasto total, o gasto em mourões e o gasto em arame, supondo que a cerca seja
feita com 4 fios de arame.
"""

lado_um = float(input("Digite a medida do lado 1 (metros): "))
lado_dois = float(input("Digite a medida do lado 2 (metros): "))
lado_tres = float(input("Digite a medida do lado 3 (metros): "))
lado_quatro = float(input("Digite a medida do lado 4 (metros): "))
preco_mourao = float(input("Digite o preço do mourão: "))
preco_arame = float(input("Digite o preço de um metro de arame farpado: "))
total_lados = lado_um + lado_dois + lado_tres + lado_quatro
total_mouroes = total_lados // 3
gasto_mouroes = total_mouroes * preco_mourao
gasto_arame = (total_lados * preco_arame) * 4
gasto_total = gasto_arame + gasto_mouroes
print(f"O gasto total foi de R${gasto_total:,.2f}")
print(f"O gasto de arames foi de R${gasto_arame:,.2f}")
print(f"O gasto de mourões foi de R${gasto_mouroes:,.2f}")
print(f"O número de mourões necessários foi de {total_mouroes} mourões")

"""São dados de entrada sobre um automóvel: modelo, marca, ano, km inicial, km final,
litros de combustível consumidos, preço por litro. Faça um algoritmo que escreva os
dados de saída da seguinte forma:
modelo_______________________ marca______________ ano________
distância percorrida ________________
litros de combustível consumidos _____________
preço por litro R$ _____________
total a pagar R$ ______________
km por litro __________
"""

modelo = str(input("Digite o modelo do carro: "))
marca = str(input("DIgite a marca do carro: "))
ano = int(input("Digite o ano do carro: "))
km_inicial = int(input("Digite o Km inicial do carro: "))
km_final = int(input("Digite o Km final do carro: "))
litros = float(input("Digite os litros de combustível consumidos: "))
preco_litro = float(input("Digite  o preço do litro: "))
dist_perc = km_final - km_inicial
km_litro = dist_perc / litros
total_pagar = litros * preco_litro

print(f"Seu carro é um modelo: {modelo}, marca: {marca}, ano: {ano}, distancia percorrida: {dist_perc}, litros de combustível consumidos: {litros}, preço por litro: {preco_litro},total a pagar: {total_pagar}, km por litro: {km_litro}")