# -*- coding: utf-8 -*-
"""ListaEstruturaDecisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eITOxF5xYLL7kfrPJhLfEb6q5jSBJ7pr

1. Ler um valor e escrever se é positivo, negativo ou zero.
"""

num = int(input("Digite um número: "))
if num < 0:
  print("Esse número é negativo.")
else:
  if num == 0:
    print("Esse número é 0")
  else:
    print("Esse número é positivo")

"""2. Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10,
caso contrário escrever NÃO É MAIOR QUE 10!
"""

num = int(input("Digite um número: "))
if num > 10:
  print("É MAIOR QUE 10!")
else:
  print("NÃO É MAIOR QUE 10!")

"""3. Calcule a soma de dois números, se o resultado for maior que 10, mostre-o na tela."""

num_um = int(input("Digite um número: "))
num_dois = int(input("Digite outro número: "))
soma = num_um + num_dois
if soma > 10:
  print(soma)

"""4. Entrar com um número e informar se ele é divisível por 5."""

num = int(input("Digite um número: "))
if num % 5 == 0 or num == 0:
  print("Esse número é divisível por 5")
else:
  print("Esse número não é divisivel por 5")

"""5. Construir um algoritmo que indique se o número digitado está entre 20 e 90 ou não."""

num = int(input("Digite um número: "))
if num > 20 and num < 90:
  print("Esse número está entre 20 e 90!")
else:
  print("Esse número não esta entre 20 e 90!")

"""6. Ler o ano atual e o ano de nascimento de uma pessoa. Escrever uma mensagem que
diga se ela poderá ou não votar este ano (não é necessário considerar o mês em que a
pessoa nasceu).
"""

ano_atual = int(input("Digite o ano atual: "))
ano_nasc = int(input("Digite o seu ano de nascimento: "))
idade = ano_atual - ano_nasc
if idade > 16:
  print("Você pode votar esse ano.")
else:
  print("Você não pode votar esse ano.")

"""7. Entrar com o ano de nascimento de uma pessoa e imprimir a idade dela. Verificar se o
ano digitado é válido.
"""

ano_nasc = int(input("Digite o seu ano de nascimento: "))
ano_atual = 2025
if ano_nasc < 0:
  print("Esse ano não existe")
else:
  print(f"Sua idade é {ano_atual - ano_nasc}")

"""8. Entrar com a idade de uma pessoa e exibir a mensagem; Maior de idade, menor de
idade ou acima de 65 anos.
"""

idade = int(input("Digite a sua idade: "))
if idade >= 18:
  print("Você é maior de idade.")
  if idade > 65:
    print("Você tem mais de 65 anos.")
else:
  print("Você é menor de idade.")

"""9. Ler as notas da 1a
. e 2a
. avaliações de um aluno. Calcular a média aritmética simples e
escrever uma mensagem que diga se o aluno foi ou não aprovado (considerar que se a
nota for igual ou maior que 6 o aluno é aprovado). Escrever também a média
calculada.
"""

nota_um = float(input("Digite a primeira nota: "))
nota_dois = float(input("Digite a segunda nota: "))
media = (nota_um + nota_dois) / 2
if media >= 6:
  print(f"Sua média foi {media}. Você passou!")
else:
  print(f"Sua média foi {media}. Você não passou!")

"""10. Escrever um algoritmo para ler duas notas de um aluno e escrever na tela a palavra
“Aprovado” se a média das duas notas for maior ou igual a 7,0. Caso a média seja
inferior a 7,0, o programa deve ler a nota do exame e calcular a média final. Se esta
média for maior ou igual a 5,0, o programa deve escrever “Aprovado”, caso contrário
deve escrever “Reprovado”.
"""

nota_um = float(input("Digite a primeira nota: "))
nota_dois = float(input("Digite a segunda nota: "))
media = (nota_um + nota_dois) / 2
if media >= 7:
  print("APROVADO")
else:
  nota_exame = float(input("Digite a sua nota do exame: "))
  media = (nota_um + nota_dois + nota_exame) / 3
  if media >= 5:
    print("APROVADO")
  else:
    print("REPROVADO")

"""11. Escrever um algoritmo para ler a quantidade de horas aula dadas por dois professores
e o valor por hora recebido por cada um. Mostrar na tela qual dos professores tem
salário total maior.
"""

quant_prof_um = int(input("Digite a quantidade de horas aulas dadas: "))
valor_prof_um = int(input("Digite o valor recebido por horado prof 1: "))
quant_prof_dois = int(input("Digite a quantidade de horas aulas dadas: "))
valor_prof_dois = int(input("Digite o valor recebido por hora do prof 2"))
salario_prof_um = quant_prof_um * valor_prof_um
salario_prof_dois = quant_prof_dois * valor_prof_dois
if salario_prof_um > salario_prof_dois:
  print("O primerio professor tem o salário maior.")
else:
  print("O segundo professor tem o salário maior.")

"""12. Faça um algoritmo que leia um número inteiro e mostre uma mensagem indicando se
este número é par ou ímpar.
"""

num = int(input("Digite um número: "))
if num % 2 == 0:
  print("Esse número é par")
else:
  print("Esse número é ímpar")

"""13. Ler o nome de 2 times e o número de gols marcados na partida. Escrever o nome do
vencedor. Caso não haja vencedor deverá ser impressa a palavra EMPATE.
"""

gols_um = int(input("Digite a quantidade de gols do primeiro time: "))
gols_dois = int(input("Digite a quantidade de gols do segundo time: "))
if gols_um > gols_dois:
  print("O primeiro time ganhou")
elif gols_um < gols_dois:
  print("O segundo time ganhou")
else:
  print("Deu empate")

"""14. Entrar com a sigla do estado de uma pessoa e imprimir uma das mensagens: “Carioca,
Paulista, Mineiro ou Outros”
"""

sigla = str(input("Digite a sigla do seu estado"))
if sigla == RJ:
  print("Carioca")
elif sigla == SP:
  print("Paulista")
elif sigla == MG:
  print("Mineiro")
else:
  print("Outros")

"""15. Um comerciante comprou um produto e quer vendê-lo com um lucro de 45% se o valor
da compra for menor que R$ 20,00; Caso contrário, o lucro será de 30%. Entrar com o
valor do produto e imprimir o valor da venda.
"""

valor = float(input("Digite o valor da compra: "))
if valor < 20:
  valor_venda = valor + (valor * 0.45)
  print(f"O valor da venda é {valor_venda}")
else:
  valor_venda = valor + (valor * 0.30)
  print(f"O valor da venda é {valor_venda}")

"""16. Entrar com um número de 1 a 12 e exibir o mês correspondente."""

numero = int(input("Digite o número do mês: "))
if numero == 1:
  print("Janeiro")
if numero == 2:
  print("Fevereiro")
if numero == 3:
  print("Março")
if numero == 4:
  print("Abril")
if numero == 5:
  print("Maio")
if numero == 6:
  print("Junho")
if numero == 7:
  print("Julho")
if numero == 8:
  print("Agosto")
if numero == 9:
  print("Setembro")
if numero == 10:
  print("Outubro")
if numero == 11:
  print("Novembro")
if numero == 12:
  print("Dezembro")

"""17. Faça um algoritmo que verifique se uma letra digitada é vogal ou consoante."""

letra = str(input("Digite uma letra: "))
if letra == 'a' or  letra == 'e' or letra == 'i' or letra == 'o' or letra == 'u':
  print("Vogal")
else:
  print("Consoante")

"""18. Ler 2 valores (considere que não serão lidos valores iguais) e escrever o maior deles."""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor diferente"))
if valorA > valorB:
  print(valorA)
else:
  print(valorB)

"""19. Ler 2 valores (considere que não serão lidos valores iguais) e escrevê-los em ordem
crescente.
"""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite um valor diferente: "))
if valorA < valorB:
  print(valorA,',', valorB)
else:
  print(valorB,',', valorA)

"""20. Ler 3 valores (considere que não serão informados valores iguais) e escrever o maior
deles.
"""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor diferente: "))
valorC = int(input("Digite outro valor diferente dos outros: "))
if valorA > valorB and valorC:
  print(valorA)
else:
  if valorB > valorC:
    print(valorB)
  else:
    print(valorC)

"""21. Ler 3 valores (considere que não serão informados valores iguais) e escrever a soma
dos 2 maiores.
"""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor diferente: "))
valorC = int(input("Digite outro valor diferente dos outros: "))
if valorA > valorB and valorA > valorC:
  if valorB > valorC:
    print(valorA + valorB)
  else:
    print(valorA + valorC)
else:
  if valorB > valorC:
    if valorC > valorA:
      print(valorB + valorC)
    else:
      print(valorB + valorA)
  else:
    if valorA > valorB:
      print(valorC + valorA)
    else:
      print(valorC + valorB)

"""22. Ler 3 valores (considere que não serão informados valores iguais) e escrevê-los em
ordem crescente.
"""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor diferente: "))
valorC = int(input("Digite outro valor diferente dos outros: "))
if valorA < valorB and valorA < valorC:
  if valorB < valorC:
    print(valorA, valorB, valorC)
  else:
    print(valorA, valorC, valorB)
else:
  if valorB < valorC:
    if valorC < valorA:
      print(valorB, valorC, valorA)
    else:
      print(valorB, valorA, valorC)
  else:
    if valorB < valorA:
      print(valorC, valorB, valorA)
    else:
      print(valorC,valorA,valorB)

"""23. Faça um algoritmo que leia as duas notas parciais obtidas por um aluno numa
disciplina ao longo de um semestre, e calcule a sua média. A atribuição de conceitos
obedece à tabela abaixo:

Média de
Aproveitamento Conceito
Entre 9.0 e 10.0 A
Entre 7.5 e 9.0 B
Entre 6.0 e 7.5 C
Entre 4.0 e 6.0 D
Entre 4.0 e zero E

O algoritmo deve mostrar na tela as notas, a média, o conceito correspondente e a
mensagem “APROVADO” se o conceito for A, B ou C ou “REPROVADO” se o conceito for D
ou E.
"""

from re import A
notaA = float(input("Digite a primeira nota: "))
notaB = float(input("Digite a segunda nota: "))
media = (notaA + notaB) / 2
if media >= 9:
  conceito = 'A'
else:
  if media >= 7.5:
    conceito = 'B'
  else:
    if media >= 6:
      conceito = 'C'
    else:
      if media >= 4:
        conceito = 'D'
      else:
        conceito = 'E'
if conceito == 'A' or conceito == 'B' or conceito == 'C':
  print(f"Suas notas foram {notaA} e {notaB}, sua média foi {media} e seu conceito foi {conceito}. Aprovado!")
else:
  print(f"Suas notas foram {notaA} e {notaB}, sua média foi {media} e seu conceito foi {conceito}. Reprovado!")

"""24. Escrever um algoritmo para ler dois valores e uma das seguintes operações a serem
executadas (codificadas da seguinte forma: 1 – Adição, 2 – Subtração, 3 – Multiplicação
e 4 – Divisão). Calcular e escrever o resultado dessa operação sobre os dois valores
lidos.
"""

valorA = float(input("Digite um valor: "))
valorB = float(input("Digite outro valor: "))
opcao = int(input("Digite a opção que você quer: "))
if opcao == 1:
  print(valorA + valorB)
elif opcao == 2:
  print(valorA - valorB)
elif opcao == 3:
  print(valorA * valorB)
elif opcao == 4:
  print(valorA / valorB)
else:
  print("OPÇÃO INVÁLIDA!")

"""25. Faça um algoritmo para calcular as raízes reais de uma equação quadrática: ax2 + bx +
c = 0. Uma equação quadrática só tem raiz reais se (b2 - 4ac) for maior ou igual a
zero. O algoritmo deverá informar as seguintes situações:
• Se o delta calculado for negativo, a equação não possui raízes reais. Informe ao
usuário e encerre o programa;
• Se o delta calculado for igual a zero a equação possui apenas uma raiz real,
informe-a ao usuário;
• Se o delta for positivo, a equação possui duas raiz reais, informe-as ao usuário.
"""

import math
valorA = int(input("Digite o valor de A: "))
valorB = int(input("Digite o valor de B: "))
valorC = int(input("Digite o valor de C: "))
delta = valorB**2 - 4*valorA*valorC
print(f"Delta: {delta}")
if delta < 0:
  print("Essa equação não possui raízes reais.")
else:
  x1 = (-(valorB) + (math.sqrt(delta))) / (2*valorA)
  x2 = (-(valorB) - (math.sqrt(delta))) / (2*valorA)
  if delta == 0:
    print(f"Essa equação só pussui uma raiz: {x1}, {x2}")
  else:
    print(f"Essa equação possui duas raizes: {x1}, {x2}")

"""26. Faça um algoritmo que leia 3 valores a, b, c, e verifique se podem ser os
comprimentos dos lados de um triângulo. Em caso afirmativo, verifique se é “triângulo
equilátero”, “triângulo isósceles” ou “triângulo escaleno”. Em caso negativo, escreva
uma mensagem: “os valores lidos não formam um triângulo”. Considere que:
• o comprimento de cada lado de um triângulo é menor que a soma dos
comprimentos dos outros lados
• um triângulo equilátero tem três lados iguais
• um triângulo isósceles tem dois lados iguais e um diferente
• um triângulo escaleno tem três lados diferentes.
"""

ladoA= int(input("Digite o lado A: "))
ladoB= int(input("Digite o lado B: "))
ladoC = int(input("Digite o lado C: "))
if ladoA > ladoB + ladoC or ladoB > ladoC + ladoA or ladoC > ladoB + ladoA:
    print("Os valores lidos não formam um trinagulo.")
else:
  if ladoA == ladoB and ladoA == ladoC:
    print("Esse triângulo é equilátero")
  else:
    if ladoB == ladoC or ladoA == ladoB or ladoA == ladoC:
      print("Esse triangulo é isóceles")
    else:
      print("Esse trinagulo é escaleno")

"""27. Escreva um algoritmo que leia 4 valores (opção, a, b, c), onde opção é um valor
inteiro e positivo e a, b, c são quaisquer valores reais. Escreva os valores lidos da
seguinte maneira:
se opção = 1 Þ escreva os 3 valores a, b, c em ordem crescente
se opção = 2 Þ escreva os 3 valores a, b, c em ordem decrescente
se opção = 3 Þ escreva os 3 valores de forma que o maior valor entre a, b, c fica
entre os outros 2.
"""

numeroA = float(input("Digite um número: "))
numeroB = float(input("Digite um número diferente: "))
numeroC = float(input("Digite outro número diferente: "))
opcao = int(input("Digite um valor de 1 a 3: "))
if opcao == 1:
  if numeroA < numeroB and numeroC:
    if numeroB < numeroC:
      print(numeroA, numeroB,numeroC)
    else:
      print(numeroA, numeroC, numeroB)
  else:
    if numeroB < numeroC:
      if numeroA < numeroC:
        print(numeroB, numeroA, numeroC)
      else:
        print(numeroB, numeroC, numeroA)
    else:
      if numeroA < numeroB:
        print(numeroC, numeroA, numeroC)
      else:
        print(numeroC, numeroB, numeroA)
if opcao == 2:
  if numeroA > numeroB and numeroC:
    if numeroB > numeroC:
      print(numeroA, numeroB,numeroC)
    else:
      print(numeroA, numeroC, numeroB)
  else:
    if numeroB > numeroC:
      if numeroA > numeroC:
        print(numeroB, numeroA, numeroC)
      else:
        print(numeroB, numeroC, numeroA)
    else:
      if numeroA > numeroB:
        print(numeroC, numeroA, numeroC)
      else:
        print(numeroC, numeroB, numeroA)
if opcao == 3:
  if numeroA > numeroB and numeroC:
    if numeroB > numeroC:
      print(numeroB, numeroA,numeroC)
    else:
      print(numeroB, numeroA, numeroC)
  else:
    if numeroB > numeroC:
      if numeroA > numeroC:
        print(numeroA, numeroB, numeroC)
      else:
        print(numeroC, numeroB, numeroA)
    else:
      if numeroA > numeroB:
        print(numeroA, numeroC, numeroC)
      else:
        print(numeroB, numeroC, numeroA)

"""28. Uma empresa decidiu conceder um aumento de salário a seus funcionários de acordo
com a tabela:

em R$ Índice de
Aumento
salário £ 400.00 15%
400.00 < salário £ 700.00 12%
700.00 < salário £ 1000.00 10%
1000.00 < salário £ 1500.00 7%
1500.00 < salário £ 2000.00 4%
salário > 2000.00 sem aumento

Faça um algoritmo que leia o salário atual de um funcionário e escreva o índice de
aumento e o valor do salário corrigido.
"""

salario = float(input("Digite o seu salário: "))
if salario <= 400:
  novo_salario = salario + (salario * 0.15)
  print(f"O seu novo salário novo é {novo_salario}, teve um aumento de 15%")
elif salario > 400 and salario <= 700:
  novo_salario = salario + (salario * 0.12)
  print(f"O seu salário é novo {novo_salario}, teve um aumento de 12%")
elif salario > 700 and salario <= 1000:
  novo_salario = salario + (salario * 0.10)
  print(f"O seu salário é novo {novo_salario}, teve um aumento de 10%")
elif salario > 1000 and salario <= 1500:
  novo_salario = salario + (salario * 0.7)
  print(f"O seu salário é novo {novo_salario}, teve um aumento de 7%")
elif salario > 1500 and salario <= 2000:
  novo_salario = salario + (salario * 0.4)
  print(f"O seu salário é novo {novo_salario}, teve um aumento de 4%")
else:
  print("O seu salário não teve aumento!")

"""29. Faça um algoritmo para calcular o reajuste salarial de um funcionário, de acordo com
os critérios abaixo:
• se salário é inferior a R$ 10.000,00 deve ter um reajuste de 55%
• se salário está entre R$ 10.000,00 (inclusive) e R$ 25.000,00 (inclusive) deve ter
um reajuste de 20%
• se salário é superior a R$ 25.000,00 deve ter um reajuste de 20%.
"""

salario = float(input("Digite o seu salário: "))
if salario < 10000:
  reajuste = salario + (salario * 0.55)
  print(f"O seu novo salário é {reajuste}")
elif salario > 10000:
  reajuste = salario + (salario * 0.20)
  print(f"O seu novo salário é {reajuste}")

"""30. Faça um algoritmo para controle de temperatura de um forno que derrete alumínio. O
programa deverá perguntar qual a temperatura que o alumínio deverá ser trabalhado e
operar nas seguintes condições:
• Se temperatura for inferior ou igual 500°C enviar uma mensagem para tela
"Temperatura Inválida";
• Se temperatura for menor do que 700°C enviar uma mensagem para tela
"Aquecimento Ligado em 100%";
• Se temperatura for menor do que 735°C enviar uma mensagem para tela
"Aquecimento Ligado em 50%";
• Se temperatura for maior ou igual 735°C enviar uma mensagem para tela
"Aquecimento Desligado";
• Se temperatura for maior do que 780°C enviar uma mensagem para tela
"Superaquecimento";
Os valores digitados devem ser inteiros e inferiores a 1000.
"""

temperatura = int(input("Digite a temperatura do forno (menor que 1000): "))
if temperatura <= 500:
  print("Temperatura Inválida")
elif temperatura > 500 and temperatura <= 700:
  print("Aquecimento ligado em 100%")
elif temperatura > 700 and temperatura < 735:
  print("Aqueciemento ligado em 50%")
elif temperatura >= 735 and temperatura < 780:
  print("Aquecimento Desligado")
elif temperatura >= 780:
  print("Superaquecimento")

"""31. Faça um algoritmo que permita a entrada de um valor de 1 a 4. Em seguida, leia dois
valores. Calcular e imprimir:
• Se valor digitado for 0, calcular e exibir a soma dos números
• Se valor digitado for 1, calcular e exibir a subtração dos números
• Se valor digitado for 2, calcular e exibir a multiplicação dos números
• Se valor digitado for 3, calcular e exibir a divisão dos números
• Se valor digitado for 4, calcular e exibir a média dos números
• Diferente de 1,2,3 ou 4, exibir a mensagem “Valor errado. Programa encerrado sem
cálculos”
"""

opcao = int(input("Digite uma opção: "))
valorA = float(input("Digte um valor: "))
valorB = float(input("Digite outro valor: "))
if opcao == 0:
  print(f"A soma dos números é {valorA + valorB}")
elif opcao == 1:
  print(f"A subtração dos números é {valorA - valorB}")
elif opcao == 2:
  print(f"A multiplicação dos números é {valorA * valorB}")
elif opcao == 3:
  print(f"A divisão dos números é {valorA / valorB}")
elif opcao == 4:
  media = (valorA + valorB) / 2
  print(f"A média dos números é {media}")
else:
  print("Valor errado! Programa encerrado sem calculos.")

"""32. Escrever um algoritmo que leia valores inteiros em duas variáveis distintas e se o resto
da divisão da primeira pela segunda for 1 mostre a soma dessas variáveis mais o resto
da divisão; se for 2 escreva se o primeiro e o segundo valor são pares ou ímpares; se
for igual a 3 multiplique a soma dos valores lidos pelo primeiro; se for igual a 4 divida
a soma dos números lidos pelo segundo, se este for diferente de zero. Em qualquer
outra situação mostre o quadrado dos números lidos.
"""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor: "))
if valorA % valorB == 1:
  print(f"Soma: {valorA + valorB}, resto: {valorA % valorB}")
elif valorA % valorB == 2:
  if valorA % 2 == 0:
    print(f"O valor A é par")
    if valorB % 2 == 0:
      print("Valor B é par")
    else:
      print("Valor B é impar")
  else:
    print("valor A é impar")
    if valorB % 2 == 0:
      print("Valor B é par")
    else:
      print("Valor B é impar")
elif valorA % valorB == 3:
  print(f"A multiplicação da soma dos valores lidos pelo primeiro é: {(valorA+valorB) * valorA}")
elif valorA % valorB == 4:
  if valorB == 0:
    print("Não é possível realizar uma divisão com 0")
  else:
    print(f"A divisão da soma dos dois números é pelo segundo é: {(valorA+valorB) / valorB}")
else:
  print(f"O quadrado desses números é: {valorA**2} e {valorB**2}")

"""33. Escreva um algoritmo que leia as idades de 2 homens e 2 mulheres (considere que as
idades dos homens serão sempre diferentes, bem como as das mulheres). Calcule e
escreva a soma das idades do homem mais velho com a mulher mais nova, e o
produto das idades do homem mais novo com a mulher mais velha.
"""

idade_mulherA = int(input("Digite a idade da primeira mulher: "))
idade_homemA = int(input("Digite a idade do primeiro homem: "))
idade_mulherB = int(input("Digite a idade da segunda mulher: "))
idade_homemB = int(input("Digite a idade do segundo homem: "))
if idade_homemA > idade_homemB:
  maiorH = idade_homemA
  menorH = idade_homemB
else:
  maiorH = idade_homemB
  menorH = idade_homemA
if idade_mulherA > idade_mulherB:
  maiorM = idade_mulherA
  menorM = idade_mulherB
else:
  maiorM = idade_mulherB
  menorM = idade_mulherA
print(f"A soma das idades do homem mais velho com a mulher mais nova: {maiorH + menorM}")
print(f"O produto das idades do homem mais novo com a mulher mais velha é: {maiorM * menorH}")

"""34. Existem números de 4 dígitos (entre 1000 e 9999) que obedecem à seguinte
característica: se dividirmos o número em dois números de dois dígitos, um composto
pela dezena e pela unidade, e outro pelo milhar e pela centena, e, ao somarmos estes
dois novos números gerando um terceiro, o quadrado deste terceiro número é
exatamente o número original de quatro dígitos. Por exemplo:
2025 -> dividindo: 20 e 25 -> somando temos 45 -> 452 = 2025.
Escreva um programa para ler um número e verificar se ele obedece a esta
característica.
"""

numero = int(input("Digite um número de 4 dígitos: "))
num1 = numero // 100
num2 = numero % 100
soma = num1 + num2
print(num1, num2)
if soma ** 2 == numero:
  print(f"Esse número obedece essa regra porque se cortarmos o {numero} em duas partes, fica {num1} e {num2}")
  print(f"E se pegarmos a soma desses números: {soma} e elevarmos ao quadrado: {soma**2}. O resultado vai ser o próprio número.")
else:
  print("Esse número não obdece essa regra!")