# -*- coding: utf-8 -*-
"""ListaChallengeEstruturaDecisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17my9RfCxofcLqLKlyNPNpVQRKOaR1poO

1. Faça um Programa que peça dois números e imprima o maior deles.
"""

numA = int(input("Digite um número: "))
numB = int(input("Digite outro número: "))
if numA > numB:
  print(f"O número {numA} é maior que o número {numB}")
else:
  print(f"O número {numB} é maior que o número {numA}")

"""2. Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo."""

valor = int(input("Digite um número: "))
if valor == 0:
  print("Esse número é 0")
else:
  if valor > 0:
    print("Esse número é positivo.")
  else:
    print("Esse número é negativo.")

"""3. Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino,
Sexo Inválido.
"""

letra = str(input("Digite uma letra: "))
if letra.upper() == "F":
  print("F - Feminino")
else:
  if letra.upper() == 'M':
    print("M- Masculino")
  else:
    print("Sexo Inválido")

"""4. Faça um Programa que verifique se uma letra digitada é vogal ou consoante."""

letra = str(input("Digite uma letra: "))
if letra.lower() == 'a' or letra.lower() == 'e' or letra.lower() == 'i' or letra.lower() == 'o'or letra.lower() =='u':
  print("Vogal")
else:
  print("Consoante")

"""5. Faça um programa para a leitura de duas notas parciais de um aluno. O programa deve calcular a média alcançada por
aluno e apresentar:
!"A mensagem "Aprovado", se a média alcançada for maior ou igual a sete;
!"A mensagem "Reprovado", se a média for menor do que sete;
!"A mensagem "Aprovado com Distinção", se a média for igual a dez.
"""

notaA = float(input("Digite a primeira nota: "))
notaB = float(input("Digite a segunda nota: "))
media = (notaA + notaB) / 2
if media == 10:
  print("Você foi Aprovado com Distinção")
else:
  if media >= 7:
    print("Você foi Aprovado")
  else:
    print("Você está Reprovado")

"""6. Faça um Programa que leia três números e mostre o maior deles."""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite um valor diferente: "))
valorC = int(input("Digite um outro valor difirente: "))
if valorA > valorB and valorA > valorC:
  maior = valorA
else:
  if valorB > valorC:
    maior = valorB
  else:
    maior = valorC
print(f"O maior valor é o valor: {maior}")

"""7. Faça um Programa que leia três números e mostre o maior e o menor deles."""

valorA = int(input("Digite um valor: "))
valorB = int(input("Digite outro valor: "))
valorC = int(input("Digite outro valor diferente: "))
if valorA > valorB and valorA > valorC:
  maior = valorA
  if valorB < valorC:
    menor = valorB
  else:
    menor = valorC
else:
  if valorB > valorC:
    maior = valorB
    if valorA < valorC:
      menor = valorA
    else:
      menor = valorC
  else:
    maior = valorC
    if valorA < valorB:
      menor = valorA
    else:
      menor = valorB
print("O maior valor é o valor: ", maior)
print("O menor valor é o valor: ", menor)

"""8. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a
decisão é sempre pelo mais barato.
"""

produtoA = float(input("Digite o preço do prudutoA: R$"))
produtoB = float(input("Digite o preço do produtoB: R$"))
produtoC = float(input("Digite o preço do produtoC: R$"))
if produtoA < produtoB and produtoA < produtoC:
  barato = produtoA
else:
  if produtoB < produtoC:
    barato = produtoB
  else:
    barato = produtoC
print(f"O produto mais barato é o produto que custa: R${barato}")

"""9. Faça um Programa que leia três números e mostre-os em ordem decrescente."""

numeroA = int(input("Digite um número: "))
numeroB = int(input("Digite outro número: "))
numeroC = int(input("Digite outro número diferente: "))
print("A:", numeroA)
print("B:", numeroB)
print("C:", numeroC)
if numeroA < numeroB and numeroA < numeroC:
  menor = numeroA
  if numeroB < numeroC:
    meio = numeroB
    maior = numeroC
  else:
    meio = numeroC
    maior = numeroB
else:
  if numeroB < numeroC:
    menor = numeroB
    if numeroC < numeroA:
      meio = numeroC
      maior = numeroA
    else:
      meio = numeroA
      maior = numeroC
  else:
    menor = numeroC
    if numeroA < numeroB:
      meio = numeroA
      maior = numeroB
    else:
      meio = numeroB
      maior = numeroA
print(f"Os números em ordem crescente são: {menor}, {meio} e {maior}")

"""10. Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno.
Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.
"""

print("M - Matutino, V - Vespertino, N - Noturno")
turno = str(input("Digite o turno em que você estuda: "))
if turno.upper() == "M":
  print("Bom Dia!")
elif turno.upper() == "V":
  print("Boa Tarde!")
elif turno.upper() == "N":
  print("Boa Noite!")
else:
  print("Valor Inválido!")

"""11. As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contraram para desenvolver
o programa que calculará os reajustes.
Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no
salário atual:
!"salários até R$ 280,00 (incluindo) : aumento de 20%
!"salários entre R$ 280,00 e R$ 700,00 : aumento de 15%
!"salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
!"salários de R$ 1500,00 em diante : aumento de 5% Após o aumento ser realizado, informe na tela:
!"o salário antes do reajuste;
!"o percentual de aumento aplicado;
!"o valor do aumento;
!"o novo salário, após o aumento.
"""

salario = float(input("Digite o seu salário: R$"))
if salario <= 280:
  porcentagem = "20%"
  aumento = salario * 0.20
else:
  if salario < 700:
    porcentagem = "15%"
    aumento = salario * 0.15
  else:
    if salario < 1500:
      porcentagem = "10%"
      aumento = salario * 0.10
    else:
      porcentagem = "5%"
      aumento = salario * 0.05
novo_salario = salario + aumento
print(f"Salario Antigo: R${salario}")
print(f"Porcentagem: {porcentagem}")
print(f"Aumento: R${aumento}")
print(f"Seu novo salário é R${novo_salario}")

"""12. Faça um programa para o cálculo de uma folha de pagamento, sabendo que os descontos são do Imposto de Renda, que
depende do salário bruto (conforme tabela abaixo) e 3% para o Sindicato e que o FGTS corresponde a 11% do Salário
Bruto, mas não é descontado (é a empresa que deposita). O Salário Líquido corresponde ao Salário Bruto menos os
descontos. O programa deverá pedir ao usuário o valor da sua hora e a quantidade de horas trabalhadas no mês.
Desconto do IR:
!"Salário Bruto até 900 (inclusive) - isento
!"Salário Bruto até 1500 (inclusive) - desconto de 5%
!"Salário Bruto até 2500 (inclusive) - desconto de 10%
!"Salário Bruto acima de 2500 - desconto de 20% Imprima na tela as informações, dispostas conforme o exemplo
abaixo. No exemplo o valor da hora é 5 e a quantidade de hora é 220.
"""

horas = int(input("Digite a quantidade de horas que você trabalha: "))
valor_h = int(input("Digite  o valor da sua hora: "))
salario_bruto = valor_h * horas
inss = salario_bruto * 0.10
fgts = salario_bruto * 0.11
if salario_bruto <= 900:
  print("Isento de Imposto de Renda")
else:
  if salario_bruto <= 1500:
    desconto = salario_bruto * 0.05
    porcentagem = "5%"
  else:
    if salario_bruto <= 2500:
      desconto = salario_bruto * 0.10
      porcentagem = "10%"
    else:
      desconto = salario_bruto * 0.20
      porcentagem = "20%"
total_desconto = desconto + inss
salario_liquido = salario_bruto - total_desconto
print(f"Salário Bruto:({valor_h}*{horas}): R${salario_bruto}")
print(f"(-) IR ({porcentagem}): R${desconto}")
print(f"(-) INSS (10%): R${inss}")
print(f"FGTS (11%): R${fgts}")
print(f"Total Descontos: R${total_desconto}")
print(f"Salario Líquido: R${salario_liquido}")

"""13. Faça um Programa que leia um número e exiba o dia correspondente da semana. (1-Domingo, 2- Segunda, etc.), se digitar
outro valor deve aparecer valor inválido.
"""

valor = int(input("Digite um valor (1-7): "))
if valor == 1:
  print("Domingo")
elif valor == 2:
  print("Segunda")
elif valor == 3:
  print("Terça")
elif valor == 4:
  print("Quarta")
elif valor == 5:
  print("Quinta")
elif valor == 6:
  print("Sexta")
elif valor == 7:
  print("Sabado")
else:
  print("Valor Inválido")

"""14. Faça um programa que lê as duas notas parciais obtidas por um aluno numa disciplina ao longo de um semestre, e calcule a
sua média. A atribuição de conceitos obedece à tabela abaixo:
Média de Aproveitamento Conceito
Entre 9.0 e 10.0 A
Entre 7.5 e 9.0 B
Entre 6.0 e 7.5 C
Entre 4.0 e 6.0 D
Entre 4.0 e zero E
O algoritmo deve mostrar na tela as notas, a média, o conceito correspondente e a mensagem “APROVADO” se o
conceito for A, B ou C ou “REPROVADO” se o conceito for D ou E.
"""

notaA = int(input("Digite a primeira nota: "))
notaB = int(input("Digite a segunda nota: "))
media = (notaA+notaB)/2
if media <=10 and media > 9:
  estado = "Aprovado"
  conceito = "A"
else:
  if media >= 7.5:
    estado = "Aprovado"
    conceito = "B"
  else:
    if media >= 6:
      estado = "Aprovado"
      conceito = "C"
    else:
      if media >= 4:
        estado = "Reprovado"
        conceito = "D"
      else:
        estado = "Reprovado"
        conceito = "E"
print(f"Notas: {notaA}, {notaB}")
print(f"Media: {media}")
print(f"Conceito: {conceito}")
print(f"Você está: {estado}")

"""15. Faça um Programa que peça os 3 lados de um triângulo. O programa deverá informar se os valores podem ser um triângulo.
Indique, caso os lados formem um triângulo, se o mesmo é: equilátero, isósceles ou escaleno.
Dicas:
!"Três lados formam um triângulo quando a soma de quaisquer dois lados for maior que o terceiro;
!"Triângulo Equilátero: três lados iguais;
!"Triângulo Isósceles: quaisquer dois lados iguais;
!"Triângulo Escaleno: três lados diferentes;
"""

ladoA = int(input("Digite um lado do triângulo: "))
ladoB = int(input("Digite outro lado do triângulo: "))
ladoC = int(input("Digite o outro lado do triângulo: "))
if ladoA + ladoB > ladoC and ladoB < ladoA + ladoC and ladoC < ladoB + ladoA:
  if ladoA == ladoB and ladoA == ladoC:
    print("Triângulo Equilátero")
  else:
    if ladoA == ladoB or ladoA == ladoC or ladoB == ladoC:
      print("Triângulo Isóceles")
    else:
      print("Triângulo Escaleno")
else:
  print("Esse triângulo não existe")

"""16. Faça um programa que calcule as raízes de uma equação do segundo grau, na forma ax2 + bx + c. O programa deverá
pedir os valores de a, b e c e fazer as consistências, informando ao usuário nas seguintes situações:
a. Se o usuário informar o valor de A igual a zero, a equação não é do segundo grau e o programa não deve fazer pedir
os demais valores, sendo encerrado;
b. Se o delta calculado for negativo, a equação não possui raizes reais. Informe ao usuário e encerre o programa;
c. Se o delta calculado for igual a zero a equação possui apenas uma raiz real; informe-a ao usuário;
d. Se o delta for positivo, a equação possui duas raiz reais; informe-as ao usuário;
"""

import math
a = int(input("Digite o valor de A: "))
if a != 0:
  b = int(input("Digite o valord e B: "))
  c = int(input("Digite o valord e C: "))
  delta = b**2 - 4*a*c
  if delta < 0:
    print("Essa equação não possui raizes reais")
  else:
    x1 = (-b + math.sqrt(delta)) / 2*a
    x2 = (-b - math.sqrt(delta)) / 2*a
    if delta == 0:
      print(f"Essa equação só possui uma raiz real: {x1}")
    else:
      print(f"Essa raiz tem duas raizes reais: {x1} e {x2} ")
else:
  print("Essa equação não é do segundo grau!")

"""17. Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não
bissexto.
"""

ano = int(input("Digite um ano: "))
if ano % 100 == 0:
  if ano % 400 == 0:
    print("Ano Bissexto")
  else:
    print("Não bissexto")
elif ano % 4 == 0:
  print("Ano bissexto")
else:
  print("Não bissexto")

"""18. Faça um Programa que peça uma data no formato dd/mm/aaaa e determine se a mesma é uma data válida."""

data = str(input("Digite uma data (dd/mm/aaaa): "))
dia = int(data[0:2])
mes = int(data[3:5])
ano = int(data[6:10])
if dia > 31 or mes > 12 or ano < 0:
  print("Data Inválida")
else:
  print("Data Válida")

"""19. Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades
do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros. Exemplo:
!"326 = 3 centenas, 2 dezenas e 6 unidades
!"12 = 1 dezena e 2 unidades Testar com: 326, 300, 100, 320, 310,305, 301, 101, 311, 111, 25, 20, 10, 21, 11, 1, 7 e 16
"""

num = int(input("Digite um número menor que 1000 e maior que 0: "))
if num < 1000 and num > 0:
  centenas = num // 100
  dezenas =  (num % 100) // 10
  unidade = num % 10
  if num >= 100:
    print(f"{centenas} centenas, {dezenas} dezenas e {unidade} unidades")
  elif num >= 10:
    print(f"{dezenas} dezenas e {unidade} unidades")
  else:
    print(f"{unidade} unidades")
else:
  print("Número inválido")

"""20. Faça um Programa para leitura de três notas parciais de um aluno. O programa deve calcular a média alcançada por aluno
e presentar:
a. A mensagem "Aprovado", se a média for maior ou igual a 7, com a respectiva média alcançada;
b. A mensagem "Reprovado", se a média for menor do que 7, com a respectiva média alcançada;
c. A mensagem "Aprovado com Distinção", se a média for igual a 10.
"""

notaA = float(input("Digite a primeira nota: "))
notaB = float(input("Digite a segunda nota: "))
notaC = float(input("Digite a terceira nota: "))
media = (notaA + notaB + notaC) / 3
if media == 10:
  msg = "Aprovado com Distinção"
elif media >= 7:
  msg = "Aprovado"
else:
  msg = "Reprovado"
print(f"Você foi {msg}")

"""21. Faça um Programa para um caixa eletrônico. O programa deverá perguntar ao usuário a valor do saque e depois informar
quantas notas de cada valor serão fornecidas. As notas disponíveis serão as de 1, 5, 10, 50 e 100 reais. O valor mínimo é
de 10 reais e o máximo de 600 reais. O programa não deve se preocupar com a quantidade de notas existentes na
máquina.
a. Exemplo 1: Para sacar a quantia de 256 reais, o programa fornece duas notas de 100, uma nota de 50, uma nota de
5 e uma nota de 1;
b. Exemplo 2: Para sacar a quantia de 399 reais, o programa fornece três notas de 100, uma nota de 50, quatro notas
de 10, uma nota de 5 e quatro notas de 1.
"""

from num2words import num2words
valor = int(input("Digite o valor que você quer sacar: "))
if valor < 10 or valor > 600:
  print("Esse valor é inválido")
else:
  centena = valor // 100
  dezena = valor % 100 // 10
  unidade = valor % 10
  msg_c = f'{num2words(centena, lang="pt_BR")} notas de 100'
  if dezena >= 5:
    if dezena == 5:
      msg_d = 'uma nota de 50'
    else:
      msg_d = f'uma nota de 50, {num2words(dezena - 5, lang="pt_BR")} notas de 10'
  else:
    msg_d = f'{dezena} notas de 10'
  if unidade >= 5:
    if unidade == 5:
      msg_u = 'e uma nota de 5'
    else:
      msg_u = f'uma nota de 5 e {num2words(unidade - 5, lang="pt_BR")} notas de 1'
  else:
    msg_u = f'e {unidade} notas de 1'
  print(f"Para sacar a quantia de {valor} reais, o programa deve fornecer {msg_c}, {msg_d}, {msg_u}")

"""22. Faça um Programa que peça um número inteiro e determine se ele é par ou impar. Dica: utilize o operador módulo (resto da
divisão).
"""

num = int(input("Digite um número: "))
if num % 2 == 0:
  print("Par")
else:
  print("Ímpar")

"""23. Faça um Programa que peça um número e informe se o número é inteiro ou decimal. Dica: utilize uma função de
arredondamento.
"""

num = float(input("Digite um número: "))
if num % 1 == 0:
  print("Número inteiro")
else:
  print("Número decimal")

"""24. Faça um Programa que leia 2 números e em seguida pergunte ao usuário qual operação ele deseja realizar. O resultado da
operação deve ser acompanhado de uma frase que diga se o número é:
a. par ou ímpar;
b. positivo ou negativo;
c. inteiro ou decimal.
"""

numA = float(input("Digite um número: "))
numB = float(input("Digite outro número: "))
opcao = str(input("Digite a opção desejada: "))
num = numA + numB
if opcao.upper() == 'A':
  if num % 2 == 0:
    resultado = 'Par'
  else:
    resultado = 'Ímpar'
elif opcao.upper() == 'B':
  if num < 0:
    resultado = 'Positivo'
  else:
    resultado = 'Negativo'
elif opcao.upper() == 'C':
  if num % 1 == 0:
    resultado = 'Inteiro'
  else:
    resultado = 'Decimal'
print(f"Esse número é: {resultado}")

"""25. Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
a. "Telefonou para a vítima?"
b. "Esteve no local do crime?"
c. "Mora perto da vítima?"
d. "Devia para a vítima?"
e. "Já trabalhou com a vítima?" O programa deve no final emitir uma classificação sobre a participação da pessoa no
crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4
como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".
"""

p1 = str(input("Telefonou para vítima: "))
p2 = str(input("Esteve no local do crime: "))
p3 = str(input("Mora perto da vítima: "))
p4 = str(input("Devia para a vítima: "))
p5 = str(input("Já trabalhou com a vítima: "))
x = 0
if p1.lower() == 'sim':
  x = x + 1
if p2.lower() == 'sim':
  x = x + 1
if p3.lower() == 'sim':
  x = x + 1
if p4.lower() == 'sim':
  x = x + 1
if p5.lower() == 'sim':
  x = x + 1
if x == 5:
  msg = "Assasino"
else:
  if x == 3 or x == 4:
    msg = "Cúmplice"
  else:
    if x == 2:
      msg = "Suspeita"
    else:
      msg = "Inocente"
print(msg)

"""26. Um posto está vendendo combustíveis com a seguinte tabela de descontos:
a. Álcool:
b. até 20 litros, desconto de 3% por litro
c. acima de 20 litros, desconto de 5% por litro
d. Gasolina:
e. até 20 litros, desconto de 4% por litro
f. acima de 20 litros, desconto de 6% por litro Escreva um algoritmo que leia o número de litros vendidos, o tipo de
combustível (codificado da seguinte forma: A-álcool, G-gasolina), calcule e imprima o valor a ser pago pelo cliente
sabendo-se que o preço do litro da gasolina é R$ 2,50 o preço do litro do álcool é R$ 1,90.
"""

