# -*- coding: utf-8 -*-
"""ListaEstruturaRepeticao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWoH9oP1e-2iyU4SJOnFuxasy-Ppe7FI

1. Faça um algoritmo que:
• leia 20 números inteiros;
• escreva os números que são negativos;
• escreva a média dos números positivos.
"""

cont = 0
cont2 = 0
soma_positivo = 0
lista = []
while cont < 20:
  num = int(input("Digite um número: "))
  if num < 0:
    print(f"{num} é negativo")
    lista.append(num)
  else:
    soma_positivo = soma_positivo + num
    cont2 = cont2 + 1
  cont += 1
media = soma_positivo/ cont2
print(f"Média dos positivos: {media:.2f}")
print(f'Números negativos: {lista}')

"""2. Faça um algoritmo que leia 15 números inteiros e escreva, para cada número lido, se é
par ou ímpar.
"""

i = 0
while i < 5:
  num = int(input("Digite um número: "))
  if num % 2 == 0:
    print("Esse número é par")
  else:
    print("Esse número é ímpar")
  i += 1

"""3. Dado um conjunto de valores inteiros positivos, determinar qual o menor e qual o
maior valor do conjunto. Um número com valor “0” (zero) indica o fim dos dados e
não deve ser considerado.
"""

num = int(input("Digite um número: " ))
if num != 0:
  maior = num
  menor = num
while num !=0:
  num = int(input("Digite outro numero: "))
  if num != 0:
    if num < menor:
      menor = num
    if num > maior:
      maior = num
print(f"O maior número é {maior}")
print(f"O menor número é {menor}")

"""4. Faça um algoritmo que calcule e escreva a soma dos números pares e a soma dos
números ímpares entre 1 e 100.
"""

i = 0
par = 0
impar = 0
while i <= 100:
  if i % 2 ==0:
    par += i
  else:
    impar += i
  i += 1
print(par)
print(impar)

"""5. Faça um algoritmo que leia a altura de 20 pessoas e calcule a média aritmética das
alturas.
"""

i = 0
soma = 0
while i < 5:
  altura = float(input("Digite a altura: "))
  soma += altura
  i += 1
media = soma / i
print(f"A média das altura é: {media}")

"""6. Faça um algoritmo que leia n valores inteiros e escreva quantos desses valores são
negativos.
"""

i = 0
lista = []
negativos = 0
while i < 5:
  num = int(input("Digite um número: "))
  if num < 0:
    lista.append(num)
    negativos += 1
  i += 1
print(lista, negativos)

"""7. Faça um algoritmo que leia a quantidade de tinta que uma caneta, e enquanto a
caneta tiver tinta para escrever, escreva “Enquanto tem tinta a caneta escreve...”.
Considere que a cada comando de escrita a caneta gasta 2% da tinta que possui.
"""

qntd = int(input("Digite a quantidade de tinta que a caneta pussui: "))
porc = 2/100 * qntd
while qntd > 0:
  print("Enquanto tem tinta a caneta escreve!")
  print(qntd,'%')
  qntd = qntd - porc

"""8. Faça um algoritmo que leia n pares de valores, sendo o primeiro valor o número de
inscrição do atleta e o segundo a altura (em cm) do atleta. Escreva:
• o número de inscrição e a altura do atleta mais alto;
• o número de inscrição e a altura do atleta mais baixo;
• a altura média do grupo de atletas.
"""

i = 0
maior = 0
menor = 0
m_ins = 0
me_ins = 0
altura = 1
soma = 0
while altura != 0:
  if i != 0 and menor == 0:
    menor = altura
    me_ins = num
  sair = int(input("Digite 0 para sair: "))
  if sair == 0:
    break
  altura = float(input("Digite a altura: "))
  num = int(input("Digite o número de inscrição: "))
  if altura > maior:
    maior = altura
    m_ins = num
  else:
    menor = altura
    me_ins = num
  i += 1
  soma += altura
media = soma / i
print(f"O atleta mais alto é o número {m_ins}, altura: {maior}")
print(f"O atleta mais baixo é o número {me_ins}, altura: {menor}")
print(f"A média do grupo de atletas é: {media:.2f}")

"""9. Faça um algoritmo que calcule e imprima os valores de y, onde:
y = (3+3x+6x²)/(1+9x+16x²), para x variando de 1.0 até 5.0, em intervalos de 0.1 unidades.
"""

x = 1
while x <= 5:
  y = (3+2*x+6*x**2)/(1+9*x+16*x**2)
  print(f'O valor de y é: {y:.2f}')
  x += 0.1

"""10. Construir um algoritmo que calcule o fatorial de um número N."""

num = int(input("Digite um número: "))
num_org = num
i = 1
while i < num_org:
  num *= i
  i += 1
print(num)

"""11. Faça um algoritmo que calcule e escreva a soma da seguinte série de 100 termos:
1+2+3+4+...+100
"""

num = 0
i = 1
while i <= 100:
  num += i
  i+=1
print(num)

"""12. Faça um algoritmo que calcule e escreva a soma da seguinte série de 100 termos:

"""

total = 0
for i in range(1, 101):
  total = total + (1/i)
print(total)

"""13. Fazer um algoritmo para calcular o valor de S, dado por:
sendo N lido.
"""

num = int(input("Digite um número: "))
S = 0
den = num
for i in range (1, num + 1):
  S = S + (i/den)
  den = den - 1
print('S = ',S)

"""14. O valor aproximado do número pi pode ser calculado usando-se a série:"""

S = 0
den = 1
for i in range(1, 52):
  if i  % 2== 0:
    S = S - (1/den**3)
  else:
    S =  S +(1/den**3)
  den = den + 2
pi = S * 32
pi = pi ** (1/3)
print(pi)

"""15. Fazer um algoritmo que calcule e escreva a soma dos 20 primeiros termos da série:"""

import math
S = 0
num = 100
i = 0
while i < 20:
  S += num/math.factorial(i)
  i += 1
  num -= 1
print(S)

"""16. Fazer um algoritmo que calcule e imprima o valor de ex através da série:

Considerar para efeitos de cálculo os 30 primeiros termos. O algoritmo deverá ler o
valor de x.
"""

import math
x = int(input("Digite o valorde x: "))
e_x = 0
i = 0
while i < 30:
  e_x += (x**i)/math.factorial(i)
  i += 1
print(f"O valor de e^{x} é: {e_x}")

"""17. Foi feita uma pesquisa de audiência de canal de TV em n casas de um determinado
bairro de Joinville, em um certo dia do mês. Na pesquisa foi utilizado um coletor de
dados portátil. Para cada casa visitada, foi fornecido o número do canal (4, 5, 9, 12) e
o número de pessoas que estavam assistindo a TV naquele horário, considerando que
em cada casa só existia uma televisão. Em casas onde a televisão estava desligada, foi
registrado zero para o número do canal e para o número de pessoas. Faça um
algoritmo que calcule e escreva, para cada emissora, o percentual de audiência.
"""

n = int(input("Quantas casas serão avaliadas: "))
somaA = 0
somaB = 0
somaC = 0
somaD = 0
soma_total = 0
for i in range(n):
  qtnd_pessoas = int(input("Digite a quantidade de pessoas que assiste televisão: "))
  canal = int(input("Digite o canal assistido: "))
  if canal == 4:
    somaA+= qtnd_pessoas
  if canal == 5:
    somaB += qtnd_pessoas
  if canal == 9:
    somaC += qtnd_pessoas
  if canal == 12:
    somaD += qtnd_pessoas
  soma_total += qtnd_pessoas
print(f"Percentual emmissora 4: {(somaA/soma_total) * 100:.2f}%")
print(f"Percentual emmissora 5: {(somaB/soma_total) * 100:.2f}%")
print(f"Percentual emmissora 9: {(somaC/soma_total) * 100:.2f}%")
print(f"Percentual emmissora 12: {(somaD/soma_total) * 100:.2f}%")

"""18. Uma companhia de teatro planeja dar uma série de espetáculos. A direção calcula que,
a R$ 5,00 o ingresso, serão vendidos 120 ingressos. Com a diminuição de R$ 0,50 no
preço dos ingressos, espera-se que haja um aumento de 26 ingressos vendidos. As
despesas estão estipuladas em R$ 200,00 independente do número de ingressos
vendidos. Faça um algoritmo que escreva uma tabela contendo o preço do ingresso, o
número de ingressos e o lucro esperado em função do preço do ingresso, fazendo-se
variar este preço de R$ 5,00 a R$ 1,00 de R$ 0,50 em R$ 0,50. Escreva também o lucro
máximo esperado, o preço e o número de ingressos correspondentes.
"""

i = 5
ing = 120
lucro_max = 0
preco_max = 0
ingresso_max = 0
print("Preço        Ingresso     Lucro")
print("--------------------------------")
while i >= 1:
  ingressos = i * ing
  lucro = ingressos - 200
  print(f"R${i:.2f}   |     {ing}   |  R${lucro:.2f}")
  i -= 0.5
  ing+=26
  if lucro > lucro_max:
    lucro_max = lucro
    preco_max = i
    ingresso_max = ing
print(f"O lucro maxímo é {lucro_max}")
print(f"O preço maxímo é {preco_max}")
print(f"O ingresso_max é {ingresso_max}")

"""19. Faça um algoritmo que leia n números inteiros e escreva, para cada número lido, os
divisores e quantidade de divisores.
EXEMPLO: número lido = 12
divisores = 1, 2, 3, 4, 6, 12

quantidade divisores = 6
"""

num = int(input("Digite um número: "))
i = 1
qnt = 0
lista = []
while i <= num:
  if num % i == 0:
    lista.append(i)
    qnt += 1
  i += 1
print(f"{num} tem {qnt} divisores")
print(f"Divisores: {lista}")

"""20. Uma máquina de biscoito está com problemas. Quando ligada, após 1 hora ela quebra
1 biscoito, na segunda hora ela quebra 3 biscoitos, na hora seguinte ela quebra 3
vezes a quantidade de biscoitos quebrados na hora anterior, e assim por diante. Faça
um algoritmo que calcule quantos biscoitos são quebrados no final de cada dia (a
máquina opera 16 horas por dia).
"""

biscoito = 0
quebrado_nahora= 1
for i in range (1, 16+1):
  biscoito += quebrado_nahora
  quebrado_nahora *= 3
print(f"A quantidade de biscoitos quebrados foi: {biscoito}")
print(quebrado_nahora)

"""21. Uma turma tem 50 alunos. Faça um algoritmo que:
• leia para cada aluno o seu nome e idade;
• escreva os nomes dos alunos que tem 18 anos;
• escreva a quantidade de alunos que tem idade acima de 20 anos.
"""

soma_vinte = 0
lista_nome = []
for i in range(5):
  nome = str(input("Digite seu nome: "))
  idade = int(input("Digite sua idade: "))
  if idade > 20:
    soma_vinte += 1
  if idade == 18:
    lista_nome.append(31nome)
print(f'A quantidade de alunos com mais de 20 anos é: {soma_vinte}')
print(f"O nome dos alunos com 18 anos são: {lista_nome}")

"""22. Faça um algoritmo que:
• leia, para n pessoas, a altura e o sexo (sexo = 'M' ou sexo = 'm' para masculino e
sexo = 'F' ou sexo = 'f' para feminino);
• escreva a média da altura das mulheres;
• escreva a média da altura da turma.
"""

n = int(input("Digite a quantidade n: "))
soma_mulheres = 0
i_m = 0
i_h = 0
soma_homens = 0
for i in range(n):
  gen = str(input("Digite o seu sexo: "))
  altura = float(input("Digite sua altura: "))
  if gen.lower() == 'f':
    soma_mulheres += altura
    i_m += 1
  if gen.lower() == 'm':
    soma_homens += altura
    i_h += 1
media_homens = soma_homens / i_h
media_mulheres = soma_mulheres / i_m
print(f"A média da altura das mulheres é: {media_mulheres:.2f}")
print(f"A média da altura dos humens é: {media_homens:.2f}")

"""23. Uma loja de departamentos oferece para seus clientes um determinado desconto de
acordo com o valor da compra efetuada. O desconto é de 20% caso o valor da compra
seja maior que R$ 500,00 e de 15% caso seja menor ou igual. Faça um algoritmo que
leia, para cada cliente, nome, endereço e valor da compra e escreva o total a pagar.
Um nome de cliente igual a ULTIMO indica o fim da entrada de dados.
"""

nome = 'a'
while nome != 'ULTIMO':
  nome = str(input("Digite o seu nome: "))
  endereco = str(input("Digite o seu endereço: "))
  valor = float(input("Digite o valor da compra: "))
  if valor <= 500:
    desconto = valor * (15/100)
    print(f"15% de Desconto. O total a pagar é: {valor - desconto}")
  else:
    desconto = valor * (20/100)
    print(f"20% de Desconto. O total a pagar é {valor - desconto}")

"""24. Faça um algoritmo que leia valores, sendo que cada valor representa a idade de uma
pessoa. Calcule e escreva a idade média do grupo de pessoas. Só devem ser
computados no cálculo valores maiores do que zero. O algoritmo deve apresentar ao
usuário a seguinte mensagem:
deseja digitar mais um valor: s (SIM) / n (NAO)?,
antes de prosseguir com a entrada de dados.
"""

i = 0
soma = 0
cont = 0
while i == 0:
  idade = int(input("Digite sua idade: "))
  if idade > 0:
    soma += idade
    cont += 1
  else:
    print("Idade Inválida")
  nao = str(input("Quer continudar? s(SIM) / n(NÃO) "))
  if nao.lower() == 's':
    i = 0
  else:
    i = 1
media = soma / cont
print(f"A idade média do grupo é: {media}")

"""25. Um hotel cobra R$ 50,00 de diária por hóspede e mais uma taxa de serviços. A taxa de
serviços é de:
• R$ 7,50 por diária, caso o número de diárias seja menor que 15;
• R$ 6,50 por diária, caso o número de diárias seja igual a 15;
• R$ 5,00 por diária, caso o número de diárias seja maior que 15.

Disciplina: Algortimos e Programação 1
Professor: Paulo César Fernandes de Oliveira, BSc, PhD

Faça um algoritmo que apresente as seguintes opções ao recepcionista:
1. encerrar a conta de um hóspede
2. verificar número de contas encerradas
3. finalizar a execução
Caso a opção escolhida seja a primeira, leia o nome e o número de diárias do hóspede
e escreva o nome e total a ser pago. Caso a opção escolhida seja a segunda, informe o
número de hóspedes que deixaram o hotel (número de contas encerradas).
"""

i = 0
lista_nome = []
print("1. Encerrar a conta de um hóspede")
print("2. Verificar número de contas encerradas")
print("3. Finalizar a execução")
while i == 0:
  opcao = int(input("Qual opção você quer? "))
  if opcao == 1:
    nome = str(input("Digite o nome do hóspede: "))
    diaria = int(input("Digite o número de dias que o hóspede ficou: "))
    lista_nome.append(nome)
    if diaria < 15:
      total = 50 + diaria * 7.5
    if diaria == 15:
      total = 50 + diaria * 6.5
    else:
      total = 50 + diaria * 5
    print(f"O total a pagar é: {total}")
  if opcao == 2:
    print(lista_nome)
    print(f"Já foram registrados {len(lista_nome)}")
  if opcao == 3:
    break

"""26. Um determinado material radioativo perde metade de sua massa a cada 50 segundos.
Dada a sua massa inicial em Kg, faça um algoritmo que determine o tempo necessário
para que essa massa se torne menor que 0,5 gramas. Escreva a massa inicial, a massa
final e o tempo.
"""

massa = float(input("Digite a massa em kg:"))
tempo = 0
massa_in = massa
while massa >= 0.5/1000:
  massa = massa / 2
  tempo+= 50
minuto = tempo // 60
segundos = tempo % 60
print(f"Massa inicial: {massa_in}kg")
print(f"Massa final: {massa*1000}g")
print(f"Demorou {minuto} minutos e {segundos} segundos")

"""27. Um motorista acaba de voltar de um feriado prolongado. Antes de sair de viagem e
imediatamente após retornar, o motorista encheu o tanque do veículo e registrou as
medidas do odômetro. Em cada parada feita durante a viagem, foi registrado o valor
do odômetro e a quantidade de combustível comprado para reabastecer o veículo
(suponha que o tanque ficou vazio e foi enchido a cada parada). Faça um algoritmo
que leia o número total de reabastecimentos feitos (incluindo o primeiro) e os dados
registrados relativos à compra de combustível. Calcule e escreva:
a) a quilometragem obtida por litro de combustível entre cada par de paradas
b) a quilometragem média obtida por litro de combustível em toda a viagem.
"""

combustivel_total = 0
distancia_total = 0
total = int(input("Digite o número total de reabastecimento feito: "))
odometro_anterior = int(input("Digite o odometro incial: "))
for i in range(1, total +1):
  comb = float(input("Digite a quantidade de combústivel que você colocou nessa parada: "))
  odometro_atual = float(input("Digite o odometro autal: "))
  while odometro_atual < odometro_anterior:
    print("O odometro atual NÃO pode ser menor que o anterior")
    odometro_atual = float(input("Digite o odometro autal: "))
  distancia_percorida = odometro_atual - odometro_anterior
  kmL = distancia_percorida / comb
  print(f"Quilometragem por litro entra a parada anterior e a paradaa atual: {kmL:.2f}km/l")
  combustivel_total += comb
  distancia_total += distancia_percorida
  odometro_anterior = odometro_atual
media = distancia_total / combustivel_total
print("A quilometragem média em toda a viagem foi de: ", media)

"""28. Em uma disputa de pingue-pongue os pontos são anotados como D, ponto para o
jogador do lado direito, e E, ponto para o jogador do lado esquerdo da mesa. Faça um
algoritmo que leia o código do ponto de cada jogada e determine o vencedor. A
partida encerra quando:
a) um dos jogadores chegar a 21 pontos e a diferença de pontos entre os jogadores for
maior ou igual a dois;
b) o jogador com mais de 21 pontos conseguir uma diferença de dois pontos sobre o
adversário, caso a primeira condição não seja atendida.
"""

vencedor = 'falso'
sumE =0
sumD =0
while vencedor == 'falso':
  ponto = str(input("Quem fez o ponto? "))
  if ponto.upper() == 'D':
    sumD +=1
  if ponto.upper() == 'E':
    sumE +=1
  print(f"PLACAR: E({sumE}) D({sumD})")
  if sumE >= 21 or sumD >= 21:
    if sumE >= sumD+2 or sumD >= sumE +2:
      vencedor = 'true'
      if sumE > sumD:
        print("VITORÓRIA DA ESQUERDA")
      else:
        print("VITÓRIA DA DIREITA")

"""29. Os regulamentos de uma competição de pesca impõem um limite no peso total de
pesca de um dia. Faça um algoritmo que leia o limite diário (em quilogramas) e então
leia o peso (em gramas) de cada peixe e escreva o peso total da pesca obtido até
aquele ponto. Quando o limite diário for excedido escreva uma mensagem e encerre a
execução do algoritmo. O algoritmo deve ainda apresentar ao usuário a seguinte
mensagem: informar o peso de mais um peixe: s (SIM) / n (NÃO)? antes de prosseguir
com a entrada de dados.
"""

limite_diario = float(input("Digite o limmite diário: "))
limite_diario *= 1000
soma = 0
while soma <= limite_diario:
  peso = float(input("Digite o peso(em gramas) do peixe: "))
  soma += peso
  opcao = str(input("Informar o peso de mais um peixe: s (SIM) / n (NÃO)?"))
  if opcao == 'n':
    break
print(f"O peso total de peixes foi de: {soma/1000} kg")
if soma > limite_diario:
  print("Limite excedido!")
else:
  print("Acabou a pesca")

"""30. Foi feita uma pesquisa do consumo mensal de energia elétrica em uma determinada
cidade. Para cada consumidor, são fornecidos os seguintes dados: número de
identificação do consumidor, quantidade de kWh consumidos durante o mês, código
do tipo de consumidor (R - residencial, C - comercial, I - industrial). Faça um algoritmo
que:
a) leia o preço do kWh por tipo de consumidor;
b) leia os dados de n consumidores;
c) escreva o número de identificação e o total a pagar, para cada consumidor;
d) escreva a quantidade total de KWh consumida para cada um dos três tipos de
consumidores;
e) escreva a quantidade média geral de consumo.
"""

precoR = float(input("Digite o preço por kWh do consumidor Residencial: "))
precoC = float(input("Digite o preço por kWh do consumidor Comercial: "))
precoI = float(input("Digite o preço por kWh do consumidor Industrial: "))
somaR = 0
somaI = 0
somaC = 0
n = int(input("Digite quantos consumidores vamos analisar: "))
for i in range(n):
  num_id = int(input("Digite o número de identificação do consumidor: "))
  qntd_kmh = float(input("Digite a quantidade de kWh consumido durante o mês: "))
  tipo = str(input("Digite o tipo de consumidor: (R - residencial, C - comercial, I - industrial)"))
  if tipo.upper() == 'R':
    preco = precoR * qntd_kmh
    somaR += qntd_kmh
  if tipo.upper() == 'C':
    preco = precoC * qntd_kmh
    somaC += qntd_kmh
  if tipo.upper() == 'I':
    preco = precoI * qntd_kmh
    somaI += qntd_kmh
  print(f"Número de Identificação: {num_id}")
  print(f"O total a pagar foi: {preco}")
print(f"Total consumo Residencial: {somaR}")
print(f"Total consumo Comercial: {somaC}")
print(f"Total consumo Industrial: {somaI}")
media = (somaR+somaI+somaC) / n
print(f"A média geral de consumo foi de: {media:.2f}")